services:
  - type: web
    name: simple-chat-server
    runtime: node
    rootDir: simple-chat-server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
